### ISSUE TITLE
How to understand the result file

### ISSUE THREAD

**Issue by aaannaw** [hillerlab/TFforge#4]
Dear author,
I got the result file:
![image](https://github.com/user-attachments/assets/a58fe633-8757-4161-9f86-7b05dca828ea)
The second column "Pearson“ is P-value？ Could I select these CNEs with Pearson < 0.05 as the candidate CNEs, whose branch scores in trait-loss branches are significant lower than the branch scores in trait-preserving branches?
Could you give me any suggestions?
Best wishes!
Na Wan

**Comment by bjlang** [comment]
Yes, the Pearson column is the p-value, whereas NoPos and NoNeg are just the number of trait-loss and trait-preserving branchen on which the statistical test was performed.
Keep in mind, though, that the p-values are uncorrected for multiple testing.

**Comment by MichaelHiller** [comment]
README is updated now. Thx for letting us know
